pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Sherlin414/BMI_CALCULATOR.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                cd "BMI Calculator"
                npm install
                '''
            }
        }

        stage('Build Project') {
            steps {
                bat '''
                cd "BMI Calculator"
                npm run build
                '''
            }
        }
    }
}
